### ISSUE TITLE
using fftconvolver for vst binary

### ISSUE THREAD

**Issue by kronihias** [HiFi-LoFi/FFTConvolver#1]
hi!
i am trying to find a suitable partioned convolution library for usage in vst plugins.
gpl forbids to distribute vst binaries as they are compiled using the non-free steinberg vst sdk.
i wanted to ask if you are ok if somebody uses your code in a gpl project and offer vst binaries of this project.
thanks,
matthias

**Comment by HiFi-LoFi** [comment]
Hi matthias,

sorry for not answering earlier, but I was more in making music than in programming music software... ;-)

Yes, it's perfectly fine for me if you use FFTConvolver in your VST plugin and also distribute VST binaries of it. I was not aware of this limitation of this license.

Do you know of any more appropriate license for this use case? Basically it's no problem for me to switch to a slightly more liberal one regarding this.

I've seen that your from Regensburg. I'm from Munich and visiting Regensburg from time to time because quite some friends live there. :-)

Servus, Uli

**Comment by kronihias** [comment]
Hi Uli,
thanks for the answer :) Musician and code writer.. nice :)
In the meantime I did reprogram the convolution engine so the question is not really relevant for me anymore.
Wanna meet in Regensburg? Let's get in contact via email: m.kronlachner@gmail.com
Ciao, Matthias

**Comment by HiFi-LoFi** [comment]
Alright, so I leave the license for now as it is, and it's no problem for me if someone distributes VST (or other) binaries.

Please feel free to contact me if the license should be adapted somehow.

Regards, Uli

**Comment by HiFi-LoFi** [comment]
I've changed the license to MIT now... :-)
